package com.prog.cnv.sys.control.system.control;

/**
 *
 * @author CHAMOD DIYAMANTHA BALASURIYA
 */
public class Message {

    public static final String SUCCESSFULLDATAINSERT = "DATA INSERT SUCCESSFULL!";
    public static final String SUCCESSFULLDATADELETE = "DATA DELETE SUCCESSFULL!";
    public static final String SUCCESSFULLDATAUPDATE = "DATA UPDATE SUCCESSFULL!";
    public static final String DATAUPDATEPERMISSION = "ARE YOU SURE TO UPDATE DATA?";
    public static final String DATAUPDATEPERMISSIONVALIDATE = "IF YOU UPDATE THIS DATA, THIS PROCESS WILL AFFECT TO THE ALL PERFORMED TRANSACTION IN THE SYSTEM!";
    public static final String DATAUPDATEPROGRAMMERNOTE = "DEVELOPERS WILL NO GURANTEE FOR THE DATA UPDATE MALFUNCTIONS FROM USER PERSPECTIVE!";
    public static final String DATAUPDATECURRUPTION = "DATA UPDATING PROCESS WILL CORUPTED!";
    public static final String DATADELETEPERMISION = "ARE YOU SURE TO DELETE DATA?";
    public static final String DATADELETEPERMISSIONVALIDATE = "IF YOU DELETE THIS DATA, ALL TRANSACTION OF THIS DATA WILL LOST FROM THE SYSTEM!";
    public static final String DATADELETEPROGRAMMERNOTE = "DEVELOPER WILL NOT GUARANTEE FOR THE DELETION PROCESS!";
    public static final String DATASEARCHFROMSEARCHFIEDL = "DATA SEARCH";
    public static final String FROMREFRESH = "FORM REFRESH TO REFRESHMENT PREVIEW";
    public static final String PRINTFORM = "PRINT A FORM!";
    public static final String PRINTREPORT = "PRINT REPORT!";
    public static final String DATAROWADDED = "DATA ROW ADDED TO THE DATA PREVIEW TABLE!";
    public static final String ENCRYPTIONALGORITHMDETECTIONERROR = "ENCRYPTION ALGORITHM DETECTING FUNCTION ERROR!";
    public static final String ENCRYPTIONERROR = "ENCRYPTION ALGORITHM ERROR!";
    public static final String CLOSEBTNANIMATIONFAIL = "CLOSE BUTTON ANIMATION FAILIUR!";
    public static final String AVATARLOCATORERROR = "CAN NOT FIND USER AVATAR!";
    public static final String UNSUPPORTEDDISPLAYOPTION = "CONNOT DISPLAY AVATAR!";
    public static final String FILENOTFOUND = "FILE IS NOT EXISTS IN DEFINED URL!";
    public static final String DBFILTERERROR = "DATA FILTERING ERROR FROM DATABASE!";
    public static final String FILEREADERFAIL = "CANNOT READ FILE!";
    public static final String DATABASEMANIPULATINGERROR = "DATA INSERT, DELETE, UPDATE ERROR!";
    public static final String PRINTFUNCTIONEXECUTEREQUEST = "IF YOU WANT TO PRINT A BILL!";
    public static final String DONTASKMEAGAIN = "DONT ASK AGAIN!";
    public static final String QUANTITYROPMISSINGMESSAGE = "STOCK HAVEN'T ENOUGH QUANTITY TO PROCESS!/n PLEASE CONTACT ADMINISTRATOR!";
    public static final String TOSENDMAIL = "ACCEPT TO SEND A EMAIL!";
    public static final String NOSELECTEDROW = "PLEASE SELECT ANY ROW!";
    public static final String PLEASEADDITEMSTOTABLE = "TABLE IS EMPTY, PLEASE ADD DATA TO PREVIEW TABLE FIRST!";
    public static final String SUCCESSFULLYREMOVEDATAFROMTABLE = "DATA REMOVE SUCCESSFULL FROM TABLE!";
    public static final String PLEASEFILLFIELDS = "PLEASE FILL THE FIELDS BEFORE ADD DATA TO PREVIEW TABLE!";
    public static final String FIELDDATANOTMACTHC = "PLEASE CHECK YOUR FIELDS!";
    public static final String THISISREQUIREADMINPRIVILIEAGE = "THIS IS REQUIRE ADMIN CONTROLS, PLEASE LOG AS ADMINISTRATOR!";
    public static final String INVALIDWITHDRAWALAMOUNT = "PLEASE ENTER VALID WITHDRAWAL AMOUNT!";
    public static final String REFRESHTHETABLE = "TABLE REFRESHING SUCCESSFULL!";
    public static final String DOYOUNEEDBILL = "DO YOU WANT A BILL!";
    public static final String SUREYOUWANTTOLOGOUT = "SURE, YOU WANT TO LOG OUT!";
}
